---
title: Oracle AI 向量搜索生成摘要
---
Oracle AI Vector Search 专为人工智能（AI）工作负载设计，允许您基于语义而非关键字来查询数据。
Oracle AI Vector Search 的最大优势之一是，可以在单一系统中将非结构化数据的语义搜索与业务数据的关系型搜索相结合。
这不仅功能强大，而且显著更高效，因为您无需添加专门的向量数据库，从而消除了多系统间数据碎片化的痛点。

此外，您的向量可以受益于 Oracle 数据库的所有强大功能，例如：

* [分区支持](https://www.oracle.com/database/technologies/partitioning.html)
* [真正应用集群可扩展性](https://www.oracle.com/database/real-application-clusters/)
* [Exadata 智能扫描](https://www.oracle.com/database/technologies/exadata/software/smartscan/)
* [跨地理分布式数据库的分片处理](https://www.oracle.com/database/distributed-database/)
* [事务](https://docs.oracle.com/en/database/oracle/oracle-database/23/cncpt/transactions.html)
* [并行 SQL](https://docs.oracle.com/en/database/oracle/oracle-database/21/vldbg/parallel-exec-intro.html#GUID-D28717E4-0F77-44F5-BB4E-234C31D4E4BA)
* [灾难恢复](https://www.oracle.com/database/data-guard/)
* [安全性](https://www.oracle.com/security/database-security/)
* [Oracle 机器学习](https://www.oracle.com/artificial-intelligence/database-machine-learning/)
* [Oracle 图数据库](https://www.oracle.com/database/integrated-graph-database/)
* [Oracle Spatial and Graph](https://www.oracle.com/database/spatial/)
* [Oracle 区块链](https://docs.oracle.com/en/database/oracle/oracle-database/23/arpls/dbms_blockchain_table.html#GUID-B469E277-978E-4378-A8C1-26D3FF96C9A6)
* [JSON](https://docs.oracle.com/en/database/oracle/oracle-database/23/adjsn/json-in-oracle-database.html)

本指南演示了如何在 Oracle AI Vector Search 中使用摘要功能，通过 OracleSummary 为您的文档生成摘要。

如果您刚开始使用 Oracle 数据库，可以考虑探索[免费的 Oracle 23 AI](https://www.oracle.com/database/free/#resources)，它提供了设置数据库环境的绝佳入门介绍。在使用数据库时，通常建议避免默认使用系统用户；相反，您可以创建自己的用户以增强安全性和定制性。有关用户创建的详细步骤，请参阅我们的[端到端指南](https://github.com/langchain-ai/langchain/blob/v0.3/cookbook/oracleai_demo.ipynb)，该指南也展示了如何在 Oracle 中设置用户。此外，了解用户权限对于有效管理数据库安全至关重要。您可以在官方的[Oracle 指南](https://docs.oracle.com/en/database/oracle/oracle-database/19/admqs/administering-user-accounts-and-security.html#GUID-36B21D72-1BBB-46C9-A0C9-F0D2A8591B8D)中了解更多关于管理用户帐户和安全性的主题。

### 先决条件

您需要安装 `langchain-oracledb` 才能使用此集成。

`python-oracledb` 驱动程序将作为 langchain-oracledb 的依赖项自动安装。

```python
# python -m pip install -U langchain-oracledb
```

### 连接到 Oracle 数据库

以下示例代码将展示如何连接到 Oracle 数据库。默认情况下，python-oracledb 以“Thin”模式运行，该模式直接连接到 Oracle 数据库。此模式不需要 Oracle 客户端库。但是，当 python-oracledb 使用这些库时，会提供一些额外的功能。当使用 Oracle 客户端库时，python-oracledb 被称为处于“Thick”模式。两种模式都具有支持 Python 数据库 API v2.0 规范的全面功能。请参阅以下[指南](https://python-oracledb.readthedocs.io/en/latest/user_guide/appendix_a.html#featuresummary)，该指南讨论了每种模式支持的功能。如果您无法使用 Thin 模式，可能需要切换到 Thick 模式。

```python
import oracledb

# 请更新为您的用户名、密码、主机名、端口和服务名
username = "<username>"
password = "<password>"
dsn = "<hostname>:<port>/<service_name>"

connection = oracledb.connect(user=username, password=password, dsn=dsn)
print("Connection successful!")
```

### 生成摘要

Oracle AI Vector Search LangChain 库提供了一套专为文档摘要设计的 API。它支持多种摘要提供程序，例如 Database、OCIGENAI、HuggingFace 等，允许用户选择最适合其需求的提供程序。要利用这些功能，用户必须按照指定配置摘要参数。有关这些参数的详细信息，请查阅 [Oracle AI Vector Search 指南手册](https://docs.oracle.com/en/database/oracle/oracle-database/23/arpls/dbms_vector_chain1.html#GUID-EC9DDB58-6A15-4B36-BA66-ECBA20D2CE57)。

***注意：*** 如果用户希望使用 Oracle 内部和默认提供程序 'database' 之外的一些第三方摘要生成提供程序，可能需要设置代理。如果您没有代理，请在实例化 OracleSummary 时移除代理参数。

```python
# 在实例化摘要和嵌入器对象时使用的代理
proxy = "<proxy>"
```

以下示例代码将展示如何生成摘要：

```python
from langchain_oracledb.utilities.oracleai import OracleSummary
from langchain_core.documents import Document

"""
# 使用 'ocigenai' 提供程序
summary_params = {
    "provider": "ocigenai",
    "credential_name": "OCI_CRED",
    "url": "https://inference.generativeai.us-chicago-1.oci.oraclecloud.com/20231130/actions/summarizeText",
    "model": "cohere.command",
}

# 使用 'huggingface' 提供程序
summary_params = {
    "provider": "huggingface",
    "credential_name": "HF_CRED",
    "url": "https://api-inference.huggingface.co/models/",
    "model": "facebook/bart-large-cnn",
    "wait_for_model": "true"
}
"""

# 使用 'database' 提供程序
summary_params = {
    "provider": "database",
    "glevel": "S",
    "numParagraphs": 1,
    "language": "english",
}

# 获取摘要实例
# 如果不需要，请移除代理
summ = OracleSummary(conn=conn, params=summary_params, proxy=proxy)
summary = summ.get_summary(
    "In the heart of the forest, "
    + "a lone fox ventured out at dusk, seeking a lost treasure. "
    + "With each step, memories flooded back, guiding its path. "
    + "As the moon rose high, illuminating the night, the fox unearthed "
    + "not gold, but a forgotten friendship, worth more than any riches."
)

print(f"Summary generated by OracleSummary: {summary}")
```

### 端到端演示

请参阅我们的完整演示指南 [Oracle AI Vector Search 端到端演示指南](https://github.com/langchain-ai/langchain/blob/v0.3/cookbook/oracleai_demo.ipynb)，以借助 Oracle AI Vector Search 构建端到端的 RAG 管道。
